# -*- coding: utf-8 -*-
"""Stock_News_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hn7d2KfVF2iNdpWslBRf8NuhNW3H9ikL
"""

import pandas as pd

# Load the dataset
file_path = 'combined_Tesla_News_data.csv'
data = pd.read_csv(file_path)

# Display first few rows to understand the structure
print(data.head())

import ast

# Function to safely extract 'name' from 'source' column
def extract_source_name(source):
    try:
        source_dict = ast.literal_eval(source)  # Convert string to dictionary
        return source_dict.get('name', None)
    except (ValueError, SyntaxError):
        return source

# Create a new column 'source_name' with extracted values
data['source_name'] = data['source'].apply(extract_source_name)

# Drop the original 'source' column if it's no longer needed
data.drop(columns=['source'], inplace=True)

data.head()

# Extract only the date part before the first comma and convert to datetime
data['date'] = data['date'].str.split(',').str[0]  # Keep the date portion
data['date'] = pd.to_datetime(data['date'], errors='coerce')  # Convert to datetime
data.head()

import pandas as pd
import matplotlib.pyplot as plt

# Assuming 'df' is your DataFrame
data['date'] = pd.to_datetime(data['date'], errors='coerce')  # Convert 'date' to datetime

# Extract the year-month component for grouping
data['year_month'] =  data['date'].dt.to_period('M')

# Group by 'year_month' and 'keyword', and count occurrences
grouped_data = data.groupby(['year_month', 'keyword']).size().reset_index(name='count')

# Filter out invalid date entries (NaT)
grouped_data = grouped_data.dropna(subset=['year_month'])

# Plotting the data
plt.figure(figsize=(12, 6))
for keyword in grouped_data['keyword'].unique():
    keyword_data = grouped_data[grouped_data['keyword'] == keyword]
    plt.plot(keyword_data['year_month'].astype(str), keyword_data['count'], marker='o', label=f'Keyword: {keyword}')

plt.xlabel('Year-Month')
plt.ylabel('Data Points Count')
plt.title('Data Points Count for Each Month by Keyword')
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

# Assuming 'data' is your DataFrame and 'title' and 'date' are columns of interest
data = data.drop_duplicates(subset=['title', 'date','keyword'], keep='first')

# Display the shape or preview the DataFrame to confirm removal of duplicates
print(data.shape)

data.head()

"""# **Text Preprocessing - not needed for chatgpt**"""

import re

# Function to clean text data
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = text.strip()  # Remove leading/trailing whitespace
    return text

# Apply text cleaning
data['cleaned_title'] = data['title'].astype(str).apply(clean_text)

data.head()

from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')  # Download necessary NLTK resources
nltk.download('punkt_tab')

# Tokenize the cleaned title
data['tokenized_title'] = data['cleaned_title'].apply(word_tokenize)

data.head()

"""# **Sentiment Analysis - Finbert**"""

!pip install transformers torch

from transformers import AutoTokenizer
import pandas as pd

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("yiyanghkust/finbert-tone")


# Tokenize using FinBERT tokenizer
tokenized_data = data['cleaned_title'].apply(lambda x: tokenizer(x, padding=True, truncation=True,max_length=512, return_tensors="pt"))

# Extract input_ids and attention_mask
data['input_ids'] = tokenized_data.apply(lambda x: x['input_ids'])
data['attention_mask'] = tokenized_data.apply(lambda x: x['attention_mask'])

data.head()

from transformers import AutoModelForSequenceClassification
import torch

# Load FinBERT model
model = AutoModelForSequenceClassification.from_pretrained("yiyanghkust/finbert-tone")

# Set the model to evaluation mode (important for inference)
model.eval()

import torch
from torch.nn.functional import softmax

# Assuming you have input_ids and attention_mask in the DataFrame
results = []

for _, row in data.iterrows():
    input_ids = row['input_ids']  # Make sure this is a torch.Tensor
    attention_mask = row['attention_mask']  # Also a torch.Tensor

    # Ensure the tensors have the correct shape (batch size, sequence length)
    # Remove the extra dimension using squeeze()
    #input_ids = input_ids.squeeze(0)
    #attention_mask = attention_mask.squeeze(0)

    # Perform inference
    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)

    # Convert logits to probabilities
    probabilities = softmax(outputs.logits, dim=1)

    # Map the sentiment class
    sentiment_labels = ["negative", "neutral", "positive"]
    predicted_class = torch.argmax(probabilities, dim=1).item()
    sentiment = sentiment_labels[predicted_class]

    # Append the result
    results.append({
        "title": row['title'],
        "sentiment": sentiment,
        "negative_prob": probabilities[0][0].item(),
        "neutral_prob": probabilities[0][1].item(),
        "positive_prob": probabilities[0][2].item()
    })

# Convert results to a DataFrame
import pandas as pd
results_df = pd.DataFrame(results)

results_df.head()

'''from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

# Initialize the sentiment analyzer
sia = SentimentIntensityAnalyzer()

# Function to get sentiment polarity
def get_sentiment(text):
    scores = sia.polarity_scores(text)
    if scores['compound'] >= 0.05:
        return 'positive'
    elif scores['compound'] <= -0.05:
        return 'negative'
    else:
        return 'neutral'

# Apply sentiment analysis
data['sentiment'] = data['cleaned_title'].apply(get_sentiment)
'''

import matplotlib.pyplot as plt

# Count the occurrences of each sentiment category
sentiment_counts = results_df['sentiment'].value_counts()

# Plotting the distribution of sentiments
plt.figure(figsize=(8, 5))
plt.bar(sentiment_counts.index, sentiment_counts.values, color='skyblue')
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Distribution of Sentiments (Positive, Negative, Neutral)')
plt.xticks(rotation=45)
plt.show()

# Creating separate DataFrames for each sentiment category
positive_data = results_df[results_df['sentiment'] == 'positive']
negative_data = results_df[results_df['sentiment'] == 'negative']
neutral_data = results_df[results_df['sentiment'] == 'neutral']

# Saving each to a separate CSV
positive_data.to_csv("positive_sentiments.csv", index=False)
negative_data.to_csv("negative_sentiments.csv", index=False)
neutral_data.to_csv("neutral_sentiments.csv", index=False)

print("Separate CSV files for positive, negative, and neutral sentiments have been created.")

results_df = results_df.merge(data[['title', 'date']], on='title', how='left')

results_df.head()

# Group by date and sentiment
sentiment_counts = results_df.groupby(['date', 'sentiment']).size().reset_index(name='count')

print(sentiment_counts.head())

# Pivot the table to have sentiments as columns
pivot_data = sentiment_counts.pivot(index='date', columns='sentiment', values='count').fillna(0)

print(pivot_data.head())

import matplotlib.pyplot as plt

# Plot the sentiment trends
pivot_data.plot(kind='line', figsize=(10, 6), marker='o')

# Add labels and title
plt.title('Sentiment Trends Over Time', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Sentiment Count', fontsize=12)
plt.xticks(rotation=45)
plt.legend(title='Sentiment')
plt.grid()

# Show the plot
plt.show()

import matplotlib.pyplot as plt

# Separate the data for positive and negative sentiments
positive_data = pivot_data['positive']
negative_data = pivot_data['negative']

# Plot positive sentiment over time
plt.figure(figsize=(10, 6))
positive_data.plot(kind='line', marker='o', color='green')
plt.title('Positive Sentiment Trends Over Time', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Positive Sentiment Count', fontsize=12)
plt.xticks(rotation=45)
plt.grid()
plt.show()

# Plot negative sentiment over time
plt.figure(figsize=(10, 6))
negative_data.plot(kind='line', marker='o', color='red')
plt.title('Negative Sentiment Trends Over Time', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Negative Sentiment Count', fontsize=12)
plt.xticks(rotation=45)
plt.grid()
plt.show()

# Calculate positive sentiment ratio
pivot_data['positive_ratio'] = pivot_data['positive'] / (pivot_data['positive'] + pivot_data['negative'])

# Mark each day as positive, neutral, or negative based on the ratio
def mark_day(row):
    if row['positive_ratio'] > 0.65:
        return 'Positive'
    elif row['positive_ratio'] < 0.30:
        return 'Negative'
    else:
        return 'Neutral'

pivot_data['day_sentiment'] = pivot_data.apply(mark_day, axis=1)

# Count the number of days for each sentiment category
day_sentiment_counts = pivot_data['day_sentiment'].value_counts()

# Plot the categorized days
plt.figure(figsize=(8, 6))
day_sentiment_counts.plot(kind='bar', color=['green', 'gray', 'red'])
plt.title('Days Categorized by Sentiment', fontsize=16)
plt.xlabel('Sentiment Category', fontsize=12)
plt.ylabel('Number of Days', fontsize=12)
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.show()

# Visualize time series of marked days
plt.figure(figsize=(10, 6))
pivot_data['day_sentiment'].value_counts().plot(kind='bar')
plt.title("Categorized Sentiment Days Count ")
plt.grid()
plt.show()

import matplotlib.pyplot as plt

# Assuming `pivot_data` has already been processed with 'positive_ratio' and 'day_sentiment'
# Calculate a numerical score for each day: +1 for Positive, -1 for Negative, 0 for Neutral
pivot_data['sentiment_score'] = pivot_data['day_sentiment'].map({'Positive': 1, 'Negative': -1, 'Neutral': 0})

# Plot the sentiment score over time
plt.figure(figsize=(12, 6))
pivot_data['sentiment_score'].plot(kind='line', marker='o', color='blue')
plt.axhline(0, color='black', linestyle='--', linewidth=1)  # Reference line for neutrality
plt.title('Daily Sentiment Score', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Sentiment Score', fontsize=12)
plt.xticks(rotation=45)
plt.grid()
plt.show()

"""# **Stock time series**"""

!pip install google-search-results

from serpapi import GoogleSearch

params = {
  "engine": "google_finance",
  "q": "TSLA:NASDAQ",
  "window": "1Y",
  "api_key": "___key____"
}

search = GoogleSearch(params)
results = search.get_dict()

# Extract the data associated with the 'graph' key
graph_data = results.get("graph", None)

# Check if graph_data exists
if graph_data:
    print("Graph Data Extracted Successfully!")
    print(graph_data)  # Print or process the graph data
else:
    print("No 'graph' key found in the results.")

import pandas as pd
import matplotlib.pyplot as plt

# Convert graph data into a pandas DataFrame
graph_df = pd.DataFrame(graph_data)

# Strip the timezone offset from the 'date' column for parsing
graph_df['date'] = graph_df['date'].str.extract(r'^(.*?)(?: UTC.*)$')[0]

# Convert the 'date' column to a datetime object
graph_df['date'] = pd.to_datetime(graph_df['date'], format='%b %d %Y, %I:%M %p')

# Sort the data by date (if not already sorted)
graph_df = graph_df.sort_values(by='date')

# Plot the time series of prices
plt.figure(figsize=(12, 6))
plt.plot(graph_df['date'], graph_df['price'], marker='o', linestyle='-', label='Price (USD)')
plt.title('Time Series of Prices', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Price (USD)', fontsize=12)
plt.xticks(rotation=45)
plt.grid()
plt.legend()
plt.show()

graph_df['week'] = graph_df['date'].dt.to_period('W').apply(lambda r: r.start_time)
# Select only numeric columns for the mean calculation
weekly_graph_df = graph_df.groupby('week', as_index=False)[['price']].mean()

# Plot the time series of prices
plt.figure(figsize=(12, 6))
plt.plot(weekly_graph_df['week'], weekly_graph_df['price'], marker='o', linestyle='-', label='Price (USD)')
plt.title('Time Series of Prices', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Price (USD)', fontsize=12)
plt.xticks(rotation=45)
plt.grid()
plt.legend()
plt.show()

"""# **Sentiment Analysis OpenAI**"""

!pip install openai==0.28

import openai

# Set your API key
openai.api_key = "_____openai_key_____"

def analyze_sentiment(news_title):
    # Structure the message
    prompt = f"""
    Analyze the following news title for stock market sentiment for the company Tesla:
    Title: "{news_title}"
    Provide the result in this JSON format:
    {{
        "positive": x percent,
        "neutral": y percent,
        "negative": z percent
    }}
    """

    # Send the request
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a stock market sentiment analyzer for Tesla."},
            {"role": "user", "content": prompt}
        ]
    )

    # Extract and return the response
    return response.choices[0].message['content']

# Example usage
news_title = "Tesla cars for first time on Chinese government purchase list."
sentiment = analyze_sentiment(news_title)
print(sentiment)

import pandas as pd
import openai
from time import sleep
import json

# Set your OpenAI API key
openai.api_key = "__________openai_key_______"
# Define a function to get sentiment analysis from GPT
def get_sentiment(news_title):
    prompt = f"""
    Analyze the following news title for stock market sentiment:
    Title: "{news_title}"
    Provide the result in this JSON format:
    {{
        "positive": x percent,
        "neutral": y percent,
        "negative": z percent
    }}
    Ensure the values are integers without any units like percent.
    Don't add any extra explanation or text outside of the JSON.
    """
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo-16k",
            messages=[
                {"role": "system", "content": "You are a stock market sentiment analyzer."},
                {"role": "user", "content": prompt}
            ]
        )
        sentiment = response.choices[0].message['content'].strip()

        # Try parsing the response as JSON
        sentiment_dict = json.loads(sentiment)
        return sentiment_dict.get('positive', 0), sentiment_dict.get('neutral', 0), sentiment_dict.get('negative', 0)
    except json.JSONDecodeError as json_error:
        print(f"JSON parsing error for title: {news_title}\nResponse: {sentiment}\nError: {json_error}")
        return None, None, None
    except Exception as e:
        print(f"Error processing title: {news_title}\nError: {e}")
        return None, None, None




# Create new columns for sentiments
data['positive'] = 0
data['neutral'] = 0
data['negative'] = 0

# Process each news title
for idx, row in data.iterrows():
    news_title = row['title']
    positive, neutral, negative = get_sentiment(news_title)
    data.at[idx, 'positive'] = positive
    data.at[idx, 'neutral'] = neutral
    data.at[idx, 'negative'] = negative
    #sleep(1)  # To avoid rate-limiting

# Save the updated dataset
output_path = "updated_dataset_with_sentiment.csv"
data.to_csv(output_path, index=False)
print(f"Dataset saved to {output_path}")

data.head()

pip install openai==0.28

import openai
import os

openai.api_key = "___________grok_key_______________"
openai.api_base = "https://api.x.ai/v1"  # Use only if a custom endpoint is confirmed.

def get_sentiment(news_title):

  prompt = f"""
    Analyze the following news title for stock market sentiment for Tesla:
    Title: "{news_title}".
    - Provide a sentiment score between 0-10.
    - higher score means more positive sentiment.
    - Output only the sentiment score. Don't add any extra explanation or text.
    """
  try:
        response = openai.ChatCompletion.create(
            model="grok-beta",
            messages= [
                        {"role": "system", "content": "You are a stock market sentiment analyzer."},
                        {"role": "user", "content": prompt},
                    ],
       )
        print(response)
        sentiment = response.choices[0].message['content']
        return sentiment

  except Exception as e:
        print(f"Error processing title: {news_title}\nError: {e}")
        return None






# Create new columns for sentiments
data['sentiment score'] = 0
# Process each news title
for idx, row in data.iterrows():
    news_title = row['title']
    score = get_sentiment(news_title)
    data.at[idx, 'sentiment score'] = score

# Save the updated dataset
output_path = "updated_dataset_with_sentiment.csv"
data.to_csv(output_path, index=False)
print(f"Dataset saved to {output_path}")



data['date'] = pd.to_datetime(data['date'])
data['sentiment score'] = pd.to_numeric(data['sentiment score'], errors='coerce').fillna(0) # Convert to numeric, replace non-numeric with 0
# Remove rows where 'sentiment score' is null
cleaned_data = data.dropna(subset=['sentiment score'])

# Convert 'date' column to datetime and sort by date
cleaned_data['date'] = pd.to_datetime(cleaned_data['date'])
plot_data = cleaned_data.sort_values('date')

# Plot the time series
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(plot_data['date'], plot_data['sentiment score'], marker='o', linestyle='-', alpha=0.7)
plt.title("Time Series of Sentiment Scores", fontsize=14)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Sentiment Score (0-10)", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

average_scores.head()

plt.figure(figsize=(12, 6))
plt.plot(average_scores['date'], average_scores['sentiment score'], marker='o', linestyle='-', alpha=0.7)
plt.title("Time Series of Average Sentiment Scores", fontsize=14)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Average Sentiment Score (0-10)", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

average_scores = data.groupby('date', as_index=False)['sentiment score'].mean()

"""# **Comparison between sentiment and stock**"""

graph_df.head()



import pandas as pd
file_path = 'updated_dataset_with_sentiment.csv'
sentiment_timeseries_data = pd.read_csv(file_path)

sentiment_timeseries_data.head()

keyword_weights = {
    'Sales': 100,
    'Stock': 100,
    'Company': 70,
    'CEO': 50,
    'Staff': 10,
    'Inflation': 10
}

sentiment_timeseries_data['date'] = pd.to_datetime(sentiment_timeseries_data['date'])

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-1, 1))
sentiment_timeseries_data['normalized sentiment score'] = scaler.fit_transform(
    sentiment_timeseries_data[['sentiment score']]
)

def adjust_sentiment(title, base_score):
    for keyword, weight in keyword_weights.items():
        if keyword.lower() in title.lower():
            return base_score * weight
    return base_score  # No keyword match

# Adjust sentiment scores based on titles
sentiment_timeseries_data['adjusted sentiment score'] = sentiment_timeseries_data.apply(
    lambda row: adjust_sentiment(row['title'], row['normalized sentiment score']),
    axis=1
)

sentiment_timeseries_data.head()

output_path = 'updated_sentiment_with_priorities.csv'
sentiment_timeseries_data.to_csv(output_path, index=False)

sentiment_timeseries_data['date'] = pd.to_datetime(sentiment_timeseries_data['date'])
sentiment_timeseries_data['adjusted sentiment score'] = pd.to_numeric(sentiment_timeseries_data['adjusted sentiment score'], errors='coerce').fillna(0) # Convert to numeric, replace non-numeric with 0
# Remove rows where 'sentiment score' is null
cleaned_data = sentiment_timeseries_data.dropna(subset=['adjusted sentiment score'])

# Convert 'date' column to datetime and sort by date
cleaned_data['date'] = pd.to_datetime(cleaned_data['date'])
plot_data = cleaned_data.sort_values('date')

# Plot the time series
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(plot_data['date'], plot_data['adjusted sentiment score'], marker='o', linestyle='-', alpha=0.7)
plt.title("Time Series of Sentiment Scores", fontsize=14)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Sentiment Score -1 to 1)", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

average_scores = sentiment_timeseries_data.groupby('date', as_index=False)['adjusted sentiment score'].mean()

plt.figure(figsize=(12, 6))
plt.plot(average_scores['date'], average_scores['adjusted sentiment score'], marker='o', linestyle='-', alpha=0.7)
plt.title("daily Time Series of Average scaled Sentiment Scores", fontsize=14)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Average Sentiment Score (0-10)", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

sentiment_timeseries_data['date'] = pd.to_datetime(sentiment_timeseries_data['date'])

# Sort the dataset by date
sentiment_timeseries_data = sentiment_timeseries_data.sort_values('date')

# Add a new column for the week of the year
sentiment_timeseries_data['week'] = sentiment_timeseries_data['date'].dt.to_period('W').apply(lambda r: r.start_time)

# Group by week and calculate the average sentiment score for each week
weekly_sentiment = sentiment_timeseries_data.groupby('week', as_index=False)['adjusted sentiment score'].mean()

plt.figure(figsize=(12, 6))
plt.plot(weekly_sentiment['week'], weekly_sentiment['adjusted sentiment score'], marker='o', linestyle='-', alpha=0.7)
plt.title("Time Series of Average scaled Sentiment Scores", fontsize=14)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Average Sentiment Score (0-10)", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

weekly_sentiment

# Merge datasets with nearest neighbor matching
aligned_week_data = pd.merge_asof(
    weekly_graph_df.sort_values('week'),
    weekly_sentiment.sort_values('week'),
    on='week',
    direction='nearest'
)

print("Aligned Data:")
print(aligned_week_data)

import matplotlib.pyplot as plt

# Plot the time series of stock prices and sentiment scores
plt.figure(figsize=(12, 6))
plt.plot(aligned_week_data['week'], aligned_week_data['price'], label='Stock Price', marker='o', linestyle='-')
plt.plot(aligned_week_data['week'], aligned_week_data['adjusted sentiment score'], label='Sentiment Score', marker='o', linestyle='--')
plt.title("Stock Price vs Sentiment Score (Aligned with Nearest Dates)", fontsize=14)
plt.xlabel("week", fontsize=12)
plt.ylabel("Values", fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Calculate Pearson correlation coefficient
correlation = aligned_week_data['price'].corr(aligned_week_data['adjusted sentiment score'])
print(f"Correlation between sentiment score and stock price: {correlation:.2f}")

# Merge datasets with nearest neighbor matching
aligned_date_data = pd.merge_asof(
    graph_df.sort_values('date'),
    average_scores.sort_values('date'),
    on='date',
    direction='nearest'
)

print("Aligned Data:")
print(aligned_date_data)

import matplotlib.pyplot as plt

# Plot the time series of stock prices and sentiment scores
plt.figure(figsize=(12, 6))
plt.plot(aligned_date_data['date'], aligned_date_data['price'], label='Stock Price', marker='o', linestyle='-')
plt.plot(aligned_date_data['date'], aligned_date_data['adjusted sentiment score'], label='Sentiment Score', marker='o', linestyle='--')
plt.title("Stock Price vs Sentiment Score (Aligned with Nearest Dates)", fontsize=14)
plt.xlabel("date", fontsize=12)
plt.ylabel("Values", fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Calculate Pearson correlation coefficient
correlation = aligned_date_data['price'].corr(aligned_date_data['adjusted sentiment score'])
print(f"Correlation between sentiment score and stock price: {correlation:.2f}")

"""# **Lag Analysis**"""

aligned_date_data = aligned_date_data.sort_values('date')

# Create lagged features for sentiment score
for lag in range(1, 7):  # Example: 1-day, 2-day, 3-day lags
    aligned_date_data[f'sentiment_lag_{lag}'] = aligned_date_data['adjusted sentiment score'].shift(lag)

# Drop rows with NaN values due to lagging
aligned_date_data = aligned_date_data.dropna()
print(aligned_date_data)

import numpy as np

# Function to calculate cross-correlation
def cross_correlation(series1, series2, max_lag):
    lags = range(-max_lag, max_lag + 1)
    correlations = [series1.corr(series2.shift(lag)) for lag in lags]
    return lags, correlations

# Cross-correlation for stock price and sentiment score
lags, correlations = cross_correlation(aligned_date_data['price'], aligned_date_data['adjusted sentiment score'], max_lag=3)
print("Lags:", lags)
print("Correlations:", correlations)

import matplotlib.pyplot as plt

# Plot cross-correlation
plt.figure(figsize=(10, 6))
plt.bar(lags, correlations, color='skyblue')
plt.axhline(0, color='gray', linestyle='--', linewidth=0.7)
plt.title('Cross-Correlation between Stock Price and Sentiment Score', fontsize=14)
plt.xlabel('Lag (days)', fontsize=12)
plt.ylabel('Correlation', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

from scipy.stats import pearsonr

r, p_value = pearsonr(aligned_date_data['price'],  aligned_date_data['sentiment_lag_2'])
print(f"Correlation: {r:.2f}, p-value: {p_value:.3f}")

